### ISSUE TITLE
diagram settings based on toml

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#335]
We already have basic [diagram based RenderConfig](https://github.com/StateSmith/StateSmith/wiki/Diagram-Based-Render-Config) for draw.io, but you have to create a bunch of nodes for it which is slow and a bit tedious.

Instead, here's an idea to use TOML to make it much easier and allow defining SmRunner settings as well:

## plantuml
NOTE the `!` directly after block comment start.
```plantuml
/'! $CONFIG : toml
[RenderConfig]
FileTop = "// Copyright blah blah"
AutoExpandedVars = """
	int count1;
	int count2;
	"""

[RenderConfig.C]
CFileExtension = ".inc"

[SmRunnerSettings]
outputStateSmithVersionInfo = false
'/
```

Example for draw.io:
![image](https://github.com/StateSmith/StateSmith/assets/274012/44674158-051d-4553-9102-3313b889fe4f)

# Tasks

- [x] draw.io - only process `$CONFIG : toml` node inside a state machine for now (not at document root).
- [x] process draw.io nodes
- [x] process plantuml comments. See https://github.com/StateSmith/StateSmith/issues/334. Maybe have it convert comment to a node so it can be processed like a draw.io node?

# Limitations
Best not to specify these `SmRunner` settings until https://github.com/StateSmith/StateSmith/issues/336 . You may encounter exceptions or the settings may just not take effect.
