### ISSUE TITLE
cli - simplified run operation

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith#422]
# Ready for testing
Test release available as dotnet tool. You may need to uninstall StateSmith.Cli dotnet tool first.
```
dotnet tool uninstall --global StateSmith.Cli
dotnet tool install --global StateSmith.Cli --version 0.18.0-feat-422-testing
```

# Info
Idea from concept PR: https://github.com/StateSmith/StateSmith/pull/373

Add a new way to execute `ss.cli run`:
```sh
ss.cli run sm1.plantuml
ss.cli run sm1.plantuml sm2.drawio.svg

ss.cli run *.plantuml
ss.cli run **/*.plantuml
ss.cli run **/*.plantuml **/*.drawio*

# depending on your shell, you may be able to use shorthand below:
ss.cli run **.plantuml

ss.cli run --watch my_sm.drawio
ss.cli run --lang=JavaScript --watch my_sm.drawio
```
General form: `ss.cli run [run-options] [files]`, but you can put files before options if you want.

The big difference is that ss.cli will not scan those files to see if they match. It will **assume** that they are valid inputs. This will be helpful for people using `.drawio.svg` files as some drawio programs have bugs and leave them in a state where they can't be easily scanned (see https://github.com/StateSmith/StateSmith/issues/341).

## Globbing
Depending on your shell, a recursive glob like `**.plantuml` may act like `*.plantuml`. You can get around this with `**/*.plantuml` as your shell will likely pass that pattern directly to `ss.cli` and it expands any wildcard glob patterns (needed for windows anyway).

If you want to see what your shell is passing to `ss.cli`, you can pass the `-v` verbose flag and you'll see all the parsed CLI arguments:

```sh
# ss.cli run **.plantuml -v
...
  "SpecificFiles": [
    "sm0.plantuml",
    "sm1.plantuml",
    "sm2.plantuml"
  ]
...
```

## Additional Info 
If you specify [files], you should not specify `--here`, `--recursive`, `--include`, `--exclude`, `--up`, `--no-csx`

### TODO
- [x] handle relative paths (to current directory)
- [x] handle absolute paths
- [x] cross platform globbing
